apiVersion: v1
kind: Service
metadata:
  name: kafka-producer-service
  labels:
    app: kafka-producer-app
spec:
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: kafka-producer-app
